/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dreamzone_ndkdemo_ndkutils_NdkJniUtils */

#ifndef _Included_com_dreamzone_ndkdemo_ndkutils_NdkJniUtils
#define _Included_com_dreamzone_ndkdemo_ndkutils_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dreamzone_ndkdemo_ndkutils_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dreamzone_ndkdemo_ndkutils_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
